evo_init_steps: 10
evo_n_steps: 15

behavior_n_bins: 10
evo_history_length: 10
evaluation_steps: 100
env_name: "architext"
run_name: ???  # Mandatory string argument that describes the run.

# Architext parameters
height: 2.0
epoch: 1
num_generation: 2  # for every prompt, generate this many number of mutations
seed: 42
batch_size: 2

mutation_model: "chatgpt"