model: architext/gptj-162M
cuda: True
gpus: 8
seed: 42
deterministic: False
fp16: False
top_p: 0.95
temp: 0.85
timeout: 5.0  # Seconds
gen_max_len: 400
batch_size: 32
evo_init_steps: 300
evo_n_steps: 600
behavior_n_bins: 12
evo_history_length: 1000
#evaluation_steps: 100
pad_token: 50256
env_name: "architext"
run_name: ???  # Mandatory string argument that describes the run.

# Architext parameters
height: 2.0
epoch: 10  # run the search loop `epoch` amount of times
num_beams: 1
mutation_model: "gpt-j"

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
