model: architext/gptj-162M
checkpoints_dir: ./checkpoints/
cuda: True
gpus: 1
seed: 42
deterministic: False
fp16: False
top_p: 0.95
temp: 0.85
timeout: 5.0  # Seconds
gen_max_len: 300
batch_size: 1
evo_init_steps: 10
evo_n_steps: 15
behavior_n_bins: 12
evo_history_length: 10
evaluation_steps: 100
pad_token: 50256
env_name: "architext"
run_name: ???  # Mandatory string argument that describes the run.

# Architext parameters
height: 2.0

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
